[[normaliz]]
arch = "aarch64"
git-tree-sha1 = "5daa640721d30362fbb7a57113bec19d84494959"
os = "macos"

    [[normaliz.download]]
    sha256 = "9e11bdc57665af915b36b19f7b35d53283d9e0d3936cdf62dc65e44bc852a10b"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.100+0/normaliz.v300.1100.100.aarch64-apple-darwin.tar.gz"
[[normaliz]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "061abce2d7f40216215a8eb8ef3a93856e306b0c"
libc = "glibc"
os = "linux"

    [[normaliz.download]]
    sha256 = "c81110b0a142b34516e36e3b0022ea3e52b8ab59ff2062e080acd333554cdde9"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.100+0/normaliz.v300.1100.100.aarch64-linux-gnu-cxx11.tar.gz"
[[normaliz]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e67fe1cee17dda35e71d0b1d3ecb34a7cdf3a02"
libc = "musl"
os = "linux"

    [[normaliz.download]]
    sha256 = "52cdf20f3fc08e22502cc2fcf578d90dedb27c1eb018eeedfb0169cb43bb5021"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.100+0/normaliz.v300.1100.100.aarch64-linux-musl-cxx11.tar.gz"
[[normaliz]]
arch = "aarch64"
git-tree-sha1 = "728125757a1b7bf89feb57caa3bf236c92400265"
os = "freebsd"

    [[normaliz.download]]
    sha256 = "e0e50f63101ec73eefd77ab005a39c51ae2d9e1bffac30256f793418bfe8c4fb"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.100+0/normaliz.v300.1100.100.aarch64-unknown-freebsd.tar.gz"
[[normaliz]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44ecb984b207f50c87639d5525b71207b29fe815"
libc = "glibc"
os = "linux"

    [[normaliz.download]]
    sha256 = "e1fa69b43e7d54747208e54a5491a8eb74b3695b264be753900c8824000f29a9"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.100+0/normaliz.v300.1100.100.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[normaliz]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9617c74024abee3282e9db65b551014f7e2886f5"
libc = "musl"
os = "linux"

    [[normaliz.download]]
    sha256 = "bca94d636a706b15a0eebde7b84be5a73c03f3681788f9d5b08f6202d8432cef"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.100+0/normaliz.v300.1100.100.armv6l-linux-musleabihf-cxx11.tar.gz"
[[normaliz]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f8b127f9233eff70fd00d14178e0f7e08eb0797"
libc = "glibc"
os = "linux"

    [[normaliz.download]]
    sha256 = "279fd9afc2b83d6ddcad9258abdf2588258600a2fe50e257442a2ac83c89c753"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.100+0/normaliz.v300.1100.100.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[normaliz]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc4c4d7a0398195046b0c046c9c43dfb44e74844"
libc = "musl"
os = "linux"

    [[normaliz.download]]
    sha256 = "881465c8d9ca703132bf4ef056053f9bfab57042243121c8e4bfa8e8011eb3de"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.100+0/normaliz.v300.1100.100.armv7l-linux-musleabihf-cxx11.tar.gz"
[[normaliz]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7c3e3de986d06a4baa669bb3d7f8bbcec55f89e"
libc = "glibc"
os = "linux"

    [[normaliz.download]]
    sha256 = "321b0d0f5519118add7c064fa1ff27d30c86e3a5ebc8ba62f754b8819b2ba414"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.100+0/normaliz.v300.1100.100.i686-linux-gnu-cxx11.tar.gz"
[[normaliz]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2fec31245566542a6377eca6c26027df43c0fa98"
libc = "musl"
os = "linux"

    [[normaliz.download]]
    sha256 = "92ddbe975239a19754833e8f98641a23cf8c2852d34a0143af8a224801a15e6a"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.100+0/normaliz.v300.1100.100.i686-linux-musl-cxx11.tar.gz"
[[normaliz]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b3aafde2ecf7500f284734145b7df14908859a8d"
libc = "glibc"
os = "linux"

    [[normaliz.download]]
    sha256 = "14ef5865772a33b6704d2af0bc80882fa6cf8d1beef69a2d5f18ec4f405d133b"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.100+0/normaliz.v300.1100.100.powerpc64le-linux-gnu-cxx11.tar.gz"
[[normaliz]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d90fedfc5a39a9e44336d0fff2147810df8868a7"
libc = "glibc"
os = "linux"

    [[normaliz.download]]
    sha256 = "6692c22d209f6030c18394eaa3199fe0ca1c2eef8afcf59f2c307dbd9deccd76"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.100+0/normaliz.v300.1100.100.riscv64-linux-gnu-cxx11.tar.gz"
[[normaliz]]
arch = "x86_64"
git-tree-sha1 = "e1d41dbb78707eb6fcd78498aec236c20161f4de"
os = "macos"

    [[normaliz.download]]
    sha256 = "81761f29fa355534b185e2c42ac6b3a562215d09823b97ef334555ccc6fc5bcb"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.100+0/normaliz.v300.1100.100.x86_64-apple-darwin.tar.gz"
[[normaliz]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d18fc30ad277c9b6a775a9f1b961864b41b792cb"
libc = "glibc"
os = "linux"

    [[normaliz.download]]
    sha256 = "a343be0a634d64f63418ee5dab666a40f25edb617d2ebb98595d4ce30500570c"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.100+0/normaliz.v300.1100.100.x86_64-linux-gnu-cxx11.tar.gz"
[[normaliz]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7f3619ae22122198e0192a4c5f8f42129b5ae06"
libc = "musl"
os = "linux"

    [[normaliz.download]]
    sha256 = "60f323b05c7bd787fc83447b3a28e782484cbe749a21ae1713517d4e023f22c1"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.100+0/normaliz.v300.1100.100.x86_64-linux-musl-cxx11.tar.gz"
[[normaliz]]
arch = "x86_64"
git-tree-sha1 = "5bface32bb5c0bb3626a00ce6fff4e8ab4b77ed8"
os = "freebsd"

    [[normaliz.download]]
    sha256 = "e51ffa729850292f752260ff68ba51087d07ea8feb751bfd0bc0707b2ead6705"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.100+0/normaliz.v300.1100.100.x86_64-unknown-freebsd.tar.gz"
