[[normaliz]]
arch = "aarch64"
git-tree-sha1 = "cf041b6d85b51bd66148e8fb2c3c27ea8849bad7"
os = "macos"

    [[normaliz.download]]
    sha256 = "97f558e9bc1bddff7da1675e40ae1d07fc8281fb1a855ce8d4cdab8ce2b69ab5"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.101+0/normaliz.v300.1100.101.aarch64-apple-darwin.tar.gz"
[[normaliz]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f8609bbb20d54aac77fbef7b8dfcc8d1b993c112"
libc = "glibc"
os = "linux"

    [[normaliz.download]]
    sha256 = "72cfbf1d222339346f9f1e6303f7e1358cd80dfb8dd96b9750abaeff9701dbe6"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.101+0/normaliz.v300.1100.101.aarch64-linux-gnu-cxx11.tar.gz"
[[normaliz]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77932456ecf5f11761a37dd71c3daf235e095829"
libc = "musl"
os = "linux"

    [[normaliz.download]]
    sha256 = "d03725af711ab733b8ce0fcef8edafb7f6b4591495bf85f87b74b14970b13212"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.101+0/normaliz.v300.1100.101.aarch64-linux-musl-cxx11.tar.gz"
[[normaliz]]
arch = "aarch64"
git-tree-sha1 = "7a21efa4418b5c5d22f251bf82d744bf6b400093"
os = "freebsd"

    [[normaliz.download]]
    sha256 = "1871f2e0b75c1de4bc908b5a552d98c049b4f4a199406c1c656f10697af1cff0"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.101+0/normaliz.v300.1100.101.aarch64-unknown-freebsd.tar.gz"
[[normaliz]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "53c985f118e4586d0c9c9995d2c9ae2243541a90"
libc = "glibc"
os = "linux"

    [[normaliz.download]]
    sha256 = "b5619a7248e1d1ab09286cf8df72da569279396f53ab2ad79c4d34c4e9f9cae4"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.101+0/normaliz.v300.1100.101.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[normaliz]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72f7589b3c61457714edba5e38ac698782c1360e"
libc = "musl"
os = "linux"

    [[normaliz.download]]
    sha256 = "9c72811124fc74111e707e87ab91469b9b5415487486eab1ceb7baec5543f4c4"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.101+0/normaliz.v300.1100.101.armv6l-linux-musleabihf-cxx11.tar.gz"
[[normaliz]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b04f8d29b24ed4f96dc848e7a65fdf80a168b279"
libc = "glibc"
os = "linux"

    [[normaliz.download]]
    sha256 = "0089d4b92bb9f47b2f1b9e526abb6b8629b49a5fe406e8f7c0b8ab960a2a0894"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.101+0/normaliz.v300.1100.101.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[normaliz]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3dfa9fcd5abc60b9ed65ec045c2a0da929769565"
libc = "musl"
os = "linux"

    [[normaliz.download]]
    sha256 = "f3483382b0e21b5b92f0236d38034700b4b034e11ddc8795532d83846723b96b"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.101+0/normaliz.v300.1100.101.armv7l-linux-musleabihf-cxx11.tar.gz"
[[normaliz]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7547ca2a5bead58edd98c3a3d6f2aa09c6ea3457"
libc = "glibc"
os = "linux"

    [[normaliz.download]]
    sha256 = "e3b7e58cfa614f9ae4afcb61679820654623e0a678b50a32bde64e53ec514fda"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.101+0/normaliz.v300.1100.101.i686-linux-gnu-cxx11.tar.gz"
[[normaliz]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28e15117dcd5fc24ccae3bd019e5991485815e24"
libc = "musl"
os = "linux"

    [[normaliz.download]]
    sha256 = "4173f008daa38f6fcceb0f94dbe68930e2179845269c40200718208835b7d840"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.101+0/normaliz.v300.1100.101.i686-linux-musl-cxx11.tar.gz"
[[normaliz]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21ccf7c9a2534fdfdf8a541a1f282fffdb067806"
libc = "glibc"
os = "linux"

    [[normaliz.download]]
    sha256 = "3dadb973861d37537852f1746b960e131cbee0b11edbd6e63c711c883c62033f"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.101+0/normaliz.v300.1100.101.powerpc64le-linux-gnu-cxx11.tar.gz"
[[normaliz]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a589f2ae876d2cdc4231b9bb950a251e99de652"
libc = "glibc"
os = "linux"

    [[normaliz.download]]
    sha256 = "5aa3b58b387b64d2e5ee1abf12382c8073898cde54825f5152073105a597585c"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.101+0/normaliz.v300.1100.101.riscv64-linux-gnu-cxx11.tar.gz"
[[normaliz]]
arch = "x86_64"
git-tree-sha1 = "bc582af1b742e91e04e649084b23a47f98620047"
os = "macos"

    [[normaliz.download]]
    sha256 = "b352fb39ef34ec1dc50ebabb37ccd05dadca2d3b4244b3bfd17b5c050b80b7be"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.101+0/normaliz.v300.1100.101.x86_64-apple-darwin.tar.gz"
[[normaliz]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c6d11c5e8a0cc881c6f13e4474109139e5e5f62"
libc = "glibc"
os = "linux"

    [[normaliz.download]]
    sha256 = "9b7293285c9118d2bcd1a44093ff9098c4c0dfe0fb648c398a1f8e8da6bafaa0"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.101+0/normaliz.v300.1100.101.x86_64-linux-gnu-cxx11.tar.gz"
[[normaliz]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "337e0fcbb9c1dd626aceb505854b3717f2743be0"
libc = "musl"
os = "linux"

    [[normaliz.download]]
    sha256 = "1dd8de6afd7ce33adc460dcb584377d27df2122f834ad973a67dec33e2180ff6"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.101+0/normaliz.v300.1100.101.x86_64-linux-musl-cxx11.tar.gz"
[[normaliz]]
arch = "x86_64"
git-tree-sha1 = "5022684a2dd1e6aaf6b43b68a7ed5afaff2b0df2"
os = "freebsd"

    [[normaliz.download]]
    sha256 = "37a60cda70297a8fce6089111d968990a378eaabc66f4b8d6d20308d7e72280e"
    url = "https://github.com/JuliaBinaryWrappers/normaliz_jll.jl/releases/download/normaliz-v300.1100.101+0/normaliz.v300.1100.101.x86_64-unknown-freebsd.tar.gz"
